# Generated by Django 5.1.2 on 2024-11-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcgFourierTransofrmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecg_transformed_list', models.TextField(null=True)),
            ],
        ),
    ]
